default: clear BasicIndexComplie complie run

runQuery: clear queryComplie runQuery

clear:
	clear

removeClass:
	rm -rf *.class

BasicIndexComplie:
	javac BasicIndex.java

complie:
	javac P1Tester.java

queryComplie:
	javac Query.java

run:
	java P1Tester

runQuery:
	java Query Basic